=== WetBanditMarv/WetBanditMarv.github.io/ProjectWebSite/VehicleCatalog.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--Tanner Rodenburg
Bellevue University
9/6/2020
Assignment 4.2 >
Create an XML schema for a catalog of cars, where each car has the child elements make,
 model, year, color, engine, number_of_doors, transmission_type, and accessories.
 The engine element has the child elements number_of_cylinders and fuel_system (carbureted or fuel injected).
 The accessories element has the attributes radio, air_conditioning, power_windows, power_steering, and power_brakes,
  each of which is required and has the possible values yes and no.!-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="vehicle_catalog" type="xs:string">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="vehicle_class" type="xs:string">
        <xs:complexType>
        <xs:sequence>
            <xs:element name="make" type="xs:string"/>
            <xs:element name="model" type="xs:string"/>
            <xs:element name="year" type="xs:integer"/>
            <xs:element name="color" type="xs:string"/>
            <xs:element name="engine" type="xs:string">
              <xs:simpleType mixed="true">
                <xs:sequence>
                  <xs:element name="number_of_cylinders">
                    <xs:simpleType>
                      <xs:restriction base="xs:integer">
                        <xs:minInclusive value="0"/>
                        <xs:minInclusive value="16"/>
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:element>
                  <xs:element name="fuel_system">
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:pattern value="carbuerted|fuel injected"/>
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:element>
                </xs:sequence>
              </xs:simpleType>
            </xs:element>
            <xs:element name="number_of_doors">
              <xs:simpleType>
                <xs:restriction base="xs:integer">
                  <xs:minInclusive value="2"/>
                  <xs:minInclusive value="6"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:element>
            <xs:element name="transmission_type" type="xs:string"/>
            <xs:element name="accessories">
              <xs:simpleType>
                <xs:sequence>
                  <xs:element name="radio" type="xs:string">
                    <xs.simpleType>
                      <xs:restriction base="xs:string">
                        <xs:pattern value="yes|no"/>
                      </xs:restriction>
                    </xs.simpleType>
                  </xs:element>
                  <xs:element name="air_conditioning" type="xs:string">
                    <xs.simpleType>
                      <xs:restriction base="xs:string">
                        <xs:pattern value="yes|no"/>
                      </xs:restriction>
                    </xs.simpleType>
                  </xs:element>
                  <xs:element name="power_steering" type="xs:string">
                    <xs.simpleType>
                      <xs:restriction base="xs:string">
                        <xs:pattern value="yes|no"/>
                      </xs:restriction>
                    </xs.simpleType>
                  </xs:element>
                  <xs:element name="power_brakes" type="xs:string">
                    <xs.simpleType>
                      <xs:restriction base="xs:string">
                        <xs:pattern value="yes|no"/>
                      </xs:restriction>
                    </xs.simpleType>
                  </xs:element>
                </xs:sequence>
              </xs:simpleType>
            </xs:element>
        </xs:sequence>
        </xs:complexType>
      </xs:element>
      </xs:sequence>
          <xs:attribute name="vehicle_number" type="xs:string"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== WetBanditMarv/WetBanditMarv.github.io/ProjectWebSite/VehicleXML.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Tanner Rodenburg
Bellevue University
9/6/2020
Assignment 4.2
Create an XML document with at least three instances of the car element defined in the XML
schema of previous exercise.  Process this document by using the previous XML schema,
 and produce a display of the raw XML document.  Create a CSS style sheet for the XML document
 and use it to override the default styles of the XML document. !-->
<?xml-stylesheet type = "text/css" href = "CarStyleSheet.css" ?>

<vehicle_catalog vehicle_number="Assignment 4.2 Car 1"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="VehicleCatalog.xsd">
<vehicle_catalog>Car #1
 <vehicle_class>SUV</vehicle_class>
  <make>Toyota</make>
  <model>Highlander</model>
  <year>2020</year>
  <color>black</color>
  <engine>gasoline
    <number_of_cylinders>6</number_of_cylinders>
    <fuel_system>fuel injected</fuel_system>
  </engine>
  <number_of_doors>4</number_of_doors>
  <transmission_type>automatic</transmission_type>
  <accessories>
    <radio>yes</radio>
    <air_conditioning>yes</air_conditioning>
    <power_windows>yes</power_windows>
    <power_steering>yes</power_steering>
    <power_brakes>yes</power_brakes>
  </accessories>
  </vehicle_catalog>

<vehicle_catalog>Car #2
    <vehicle_class>Sedan</vehicle_class>
    <make>Oldsmobile</make>
    <model>Cutlass</model>
    <year>1990</year>
    <color>silver</color>
    <engine>gasoline
      <number_of_cylinders>8</number_of_cylinders>
      <fuel_system>carbuerted</fuel_system>
    </engine>
    <number_of_doors>4</number_of_doors>
    <transmission_type>automatic</transmission_type>
    <accessories>
      <radio></radio>
      <air_conditioning>yes</air_conditioning>
      <power_windows>no</power_windows>
      <power_steering>no</power_steering>
      <power_brakes>no</power_brakes>
    </accessories>
    </vehicle_catalog>

<vehicle_catalog>Car #3
    <vehicle_class>Sedan</vehicle_class>
    <make>Subaru</make>
    <model>Impreza WRX</model>
    <year>2015</year>
    <color>Blue</color>
    <engine>gasoline
      <number_of_cylinders>4</number_of_cylinders>
      <fuel_system>fuel injected</fuel_system>
    </engine>
    <number_of_doors>4</number_of_doors>
    <transmission_type>manual</transmission_type>
    <accessories>
      <radio>yes</radio>
      <air_conditioning>yes</air_conditioning>
      <power_windows>yes</power_windows>
      <power_steering>yes</power_steering>
      <power_brakes>yes</power_brakes>
    </accessories>
    </vehicle_catalog>
    </vehicle_catalog>
